name: 'C++ CI'

on:
  push:
    branches:
      - hw-8

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
      - name: Prepare build.sh
        run: chmod +x build.sh
      #- name: Test
      #  run: ./build.sh ${{ github.run_number }} ON bayan_test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Execute program on linux
        run: |
          sudo apt install -y ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/release/bayan-0.0.${{ github.run_number }}-Linux.deb
          bayan test 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}

  build-macos:
    name: Build on MacOS
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Download boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
            boost_version: 1.81.0
            platform_version: 12
      #- name: Test
      #  run: ./build.sh ${{ github.run_number }} ON ipfilter_lib_test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
