name: 'C++ CI'

on:
  push:
    branches:
      - master
      - hw-2

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: ./build.sh ${{ github.run_number }} ON test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
      - name: Execute program on linux
        run: |
          sudo apt install -y build/releae/ip_filter-0.0.${{ github.run_number }}-Linux.deb
          cat ip_filter.tsv | ip_filter | md5sum
  
  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: ./build.sh ${{ github.run_number }} ON test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}

