name: 'C++ CI'

on:
  push:
    branches:
      - master
      - hw-2

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Test
        run: ./build.sh ${{ github.run_number }} ON ipfilter_lib_test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Execute program on linux
        run: |
          sudo apt install -y ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/build/release/ipfilter_lib-0.0.${{ github.run_number }}-Linux.deb
          cat ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ip_filter.tsv | ip_filter | md5sum
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare build.sh
        run: chmod +x build.sh
      - name: Test
        run: ./build.sh ${{ github.run_number }} ON ipfilter_lib_test
      - name: Build
        run: ./build.sh ${{ github.run_number }} OFF package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}

